<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Images\EmailIcon.png" />
    <None Remove="Assets\Images\LoginBackground.png" />
    <None Remove="Assets\Images\Logo.png" />
    <None Remove="Assets\Images\LogoLumentra.png" />
    <None Remove="Assets\Images\LumentraFeedBanner.png" />
    <None Remove="Assets\Images\PasswordIcon.png" />
    <None Remove="Assets\Images\UserIcon.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ViewModel\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Images\EmailIcon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\LoginBackground.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Logo.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\LogoLumentra.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\LumentraFeedBanner.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\PasswordIcon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\UserIcon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
