<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="AppSettings.json" />
    <None Remove="Assets\Images\AbstractLogo.png" />
    <None Remove="Assets\Images\AbstractLogoPNG.png" />
    <None Remove="Assets\Images\EmailIcon.png" />
    <None Remove="Assets\Images\Feedbanner.jpg" />
    <None Remove="Assets\Images\LoginBackground.png" />
    <None Remove="Assets\Images\Logo.png" />
    <None Remove="Assets\Images\LogoLumentra.png" />
    <None Remove="Assets\Images\LogoModified.png" />
    <None Remove="Assets\Images\LumentraFeedBanner.png" />
    <None Remove="Assets\Images\PasswordIcon.png" />
    <None Remove="Assets\Images\UserIcon.png" />
    <None Remove="FeedVideos.json" />
    <None Remove="Notification.json" />
    <None Remove="VideoThumbnails\csharpVideo.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ViewModel\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0" />
    <PackageReference Include="System.Text.Json" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="AppSettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Resource Include="Assets\Images\AbstractLogo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\AbstractLogoPNG.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\EmailIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Feedbanner.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\LoginBackground.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\LogoLumentra.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\LogoModified.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\LumentraFeedBanner.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\PasswordIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\UserIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Content Include="FeedVideos.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Notification.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Resource Include="VideoThumbnails\csharpVideo.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
